### ISSUE TITLE
extendObservable and map() - unexpected behavior

### ISSUE THREAD

**Issue by nightwolfz** [mweststrate/mobservable#100]
```
var that = {};
extendObservable(that, {
    myMap: map();
})
console.log(that.myMap)
```
returns
```
Object {$mobservable: Object, _data: Object, _hasMap: Object, _keys: Array[0], _events: Object…}
```
This object is not observable and has no .observe on it's prototype.

Now if we declare it this way:
```
that.myMap = map();
console.log(that.myMap)
```
returns
```
ObservableMap {$mobservable: Object, _data: Object, _hasMap: Object, _keys: ObservableArray[0], _events: SimpleEventEmitter…}
```
This object is observable and everything is OK.

**Comment by mweststrate** [comment]
Hi @nightwolfz could you take a look at the above commit and compare it with your setup? I tried to reproduce your issue but everything seems to work as expected.

**Comment by nightwolfz** [comment]
Thanks for the reply but it seems like I jumped to this conclusion way too early.
I didn't realize you cannot serialize maps properly.

We can close this issue :)
