### ISSUE TITLE
Decorators are not supported yet in 6.x pending proposal update.

### ISSUE THREAD

**Issue by davidmoshal** [mweststrate/mobservable#105]
Just tried mobservable in my project, though ran into this issue:

Module build failed: SyntaxError:    
Decorators are not supported yet in 6.x pending proposal update.

```
  20 | 
  21 | @observer
> 22 | class TimerView extends Component {
     | ^
  23 |   render() {
  24 |     return (
  25 |       <button onClick={this.onReset}>
```

Here is my `.babelrc`:

```js
{
  "presets": [
    "react",
    "es2015",
    "stage-1"
  ],
  "env": {
    "development": {
      "presets": [
        "react-hmre"
      ]
    }
  }
}
```

**Comment by davidmoshal** [comment]
found the solution:
- http://technologyadvice.github.io/es7-decorators-babel6/
- npm i --save-dev babel-plugin-transform-decorators-legacy
```js
# .babelrc
{
  "presets": [
    "react",
    "es2015",
    "stage-1"
  ],
  "plugins": ["transform-decorators-legacy"]
}

```

**Comment by mweststrate** [comment]
Thanks for figuring this out! I updated the tests and will update the docs soon

**Comment by mweststrate** [comment]
@kmalakoff ^ how to enable decorators in babel 6

**Comment by davidmoshal** [comment]
no problem, glad it helped
Dave

**Comment by mweststrate** [comment]
As reported here: https://github.com/mobxjs/mobx-react/issues/41 it appears that the order of plugins is important, make sure that `transform-decorators-legacy

**Comment by daisuke-3** [comment]
I have the save problem.
It works fine like this.

```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["transform-decorators-legacy", "transform-decorators"]
}
```

**Comment by andreyluiz** [comment]
Well, my config is exactly the same as described by @davidmoshal but I am getting an `Uncaught TypeError: decorator is not a function` in the Chrome console. Webpack bundles it correctly.
```
{
  test: /\.js$/,
  exclude: /(node_modules|bower_components)/,
  loader: 'babel', // 'babel-loader' is also a legal name to reference
  cacheDirectory: true,
  query: {
    plugins: [
      "transform-decorators-legacy",
    ],
    presets: ['react', 'es2015', 'stage-1']
  }
}
```

My dependencies:

```
"devDependencies": {
  "babel-cli": "^6.10.1",
  "babel-core": "^6.10.4",
  "babel-loader": "^6.2.4",
  "babel-plugin-transform-decorators-legacy": "^1.3.4",
  "babel-preset-es2015": "^6.9.0",
  "babel-preset-react": "^6.11.1",
  "babel-preset-stage-1": "^6.5.0",
  "mobx": "^2.3.6",
  "mobx-react": "^3.5.0",
  "react": "^15.2.1",
  "react-dom": "^15.2.1",
  "webpack": "^1.13.1"
}
```

Am I missing something?

**Comment by adamski** [comment]
I had this come up, after adding a new preset to my `.babelrc`. Solved by switching them around:
```
{
  "presets": ["stage-2", "react-native-stage-0/decorator-support"],
}
```

**Comment by mweststrate** [comment]
So with this setup you don't need `transform-decorators-legacy`?

Op do 6 okt. 2016 om 00:04 schreef Adam Wilson <notifications@github.com>:

**Comment by adamski** [comment]
No, that's what `react-native-stage-0/decorator-support` does

**Comment by nikitph** [comment]
i have tried everything in this thread and i still get "leading decorators must be attached to a class" i m on latest everything. any suggestions? i would hate to go to redux.

**Comment by mweststrate** [comment]
@nikitph note that all decorators are optional! See http://mobxjs.github.io/mobx/best/decorators.html

**Comment by nikitph** [comment]
i know.. but i m from a java background and find decorators to be much more
intuitive and clear. And then there is the question of confidence. i know
redux to b involved and has lots of boilerplate but it has a very strong
community behind it. i have spent nearly 4 hours so far watching mobx
videos and while conceptually i find it way better, unable to get started
with the most basic of things is not inspiring me to use it in production.

**Comment by mweststrate** [comment]
Can you share your setup and config files? React / react Native /
TypeScript / Babel etc

Op di 25 okt. 2016 om 21:23 schreef nikit <notifications@github.com>:

> i know.. but i m from a java background and find decorators to be much more
> intuitive and clear. And then there is the question of confidence. i know
> redux to b involved and has lots of boilerplate but it has a very strong
> community behind it. i have spent nearly 4 hours so far watching mobx
> videos and while conceptually i find it way better, unable to get started
> with the most basic of things is not inspiring me to use it in production.
>
> On Tue, Oct 25, 2016 at 10:47 AM, Michel Weststrate <

**Comment by DigitalMarc** [comment]
Hi guys, 
Within this config:
```
"babel": {
    "presets": ["es2015", "stage-0", "react"],
  "plugins": ["transform-decorators-legacy", "transform-decorators"]
  },
```
For this bit of code:

```
@computed get completedTodosCount() {
    	return this.todos.filter(
			todo => todo.completed === true
		).length;
    }
```
I got this output: 
` Method has decorators, put the decorator plugin before the classes one.`

**Comment by mweststrate** [comment]
@DigitalMarc afaik `transform-decorators` should not be needed

**Comment by DigitalMarc** [comment]
@mweststrate cheers, all that MobX stuff is great and I would definitely like having those decorators working.
 If you have any recommendation / setup to follow to make this work, that would be great.

**Comment by mweststrate** [comment]
@DigitalMarc are you using react or react-native? Are you sure `.babelrc` is picked up at all? Sometimes it is duplicated in webpack configs etc. Did you install the corresponding babel packages? I assume you are using babel 6?

**Comment by DigitalMarc** [comment]
hey @mweststrate, thanks for your feedback. I'm using react, testing next.js so the problem might come from there. Babel presets are loaded for the 'package.json' file located at the root of the project structure. I've installed all the Babel package I can dream of and tested different combination.

**Comment by mweststrate** [comment]
@DigitalMarc ah! check: https://github.com/zeit/next.js/issues/26. Edit: see you already found it. Yeah I think the issue is probably that the plugins don't get the right priority. If it is just for testing / play, you might try to modify the babelrc of next itself in your node_modules (or by creating a fork), that should give some clue whether this is indeed the issue

**Comment by MarcMagnin** [comment]
@mweststrate, Thanks mate, I'll give a try.
Thumbs up for the really good work.

**Comment by wss1942** [comment]
Update the `webpack.config.js`:  
```
  "babel": {
    "presets": [
      "react-app"
    ],
    "plugins": ["transform-decorators-legacy"]     //++
  },
```

**Comment by mingyuanke** [comment]
if use `creact-react-app`,update `react-scripts`
```
{
            test: /\.(js|jsx)$/,
            include: paths.appSrc,
            loader: require.resolve('babel-loader'),
            options: {
              // @remove-on-eject-begin
              babelrc: true, //**update false to true**
              presets: [require.resolve('babel-preset-react-app')],
              // @remove-on-eject-end
              compact: true,
            },
          }
```

**Comment by TamerCC** [comment]
My solution was
**.babelrc**
`{
  "presets": [
    "react",
    "es2015",
    "stage-1"
  ],
  "plugins": ["transform-decorators-legacy" /* should always be the first plugin! */]
}
`
**webpack.config.js**
`module: {
    rules: [ // loader rules
      {
        test: /\.js$/, // files ending with .js
        exclude: /node_modules/, // exclude the node_modules directory
        loader: 'babel-loader', // use this (babel-core) loader
        query: {
          "presets": ["react", "env", "stage-0"],
          "plugins": ["transform-decorators-legacy"]
        }
      },`

**Comment by cpprookie** [comment]
Hey guys, i got a problem about mobx envirnoment.
I have .babelrc file like this
```
{
  "presets": ["es2015"],
  "plugins": ["transform-decorators-legacy"]
}
```
And i intall babel-preset and babel-plugin which is needed. After test, i could use decorator in my project. But when it comes to mobx use like 
```
import { observable } from 'mobx';
export default class Timer {
  @observable timer = 0;
}
```
I got output `SyntaxError: index.js: Unexpected token ` at **timer = 0**, what should i do to fix it? I have knowed that  decorator should work with class/function, Any extra configuration is needed whe n i want to create observable properties?

**Comment by andykog** [comment]
You need babel-plugin-transform-class-properties

**Comment by cpprookie** [comment]
If anyone have question like me? You may need add `"stage-1"` in your .babelrc presets, And install related modules.You can Check [es6-class-member-variable](https://stackoverflow.com/questions/36140164/declaration-of-member-variables-in-es6-classes).

**Comment by guanbiao33** [comment]
@cpprookie I got the same error and fixed it,thank you

**Comment by wnbupt** [comment]
please make sure that `"babel-loader": "^7.1.1"`
> In Babel 7, transform-decorators-legacy will be the default plugin in Stage-0.
From https://babeljs.io/docs/plugins/transform-decorators/#top

**Comment by blusclips** [comment]
tried to configure my .babelrc file..
{
  "presets": ["es2015", "stage-1"],
  "plugins": ["transform-decorators-legacy"]
}

 Plugin/Preset files are not allowed to export objects, only functions.

**Comment by WangSongYang** [comment]
I config my .babelrc files like this:
{
    "preset": ["react-native", "es2015", "stage-1"],
    "plugins": ["transform-decorators-legacy"]
}
but, after I run "react-native run-ios', I got this error message--"Plugin/preset files are not allowed to export objects, only functions."

Is there some one helping me ? Thanks.
