### ISSUE TITLE
How to get 

### ISSUE THREAD

**Issue by rodryquintero** [mweststrate/mobservable#106]
In red you will see an observable object that has a property with a collection of objects.

![image](https://cloud.githubusercontent.com/assets/1271370/12700972/bc7658ae-c7c6-11e5-9a85-789f1e167c31.png)

But what I really want is to have access to an object, not an array. For some reason **observe** creates an array from the object that represents the store values. 

Here is the part of the store class that is affected.
```
class Hosts {

    constructor(props) {
      this.URL = 'TRACER.wsHCAConfigurations.cls';
      this.hosts = observable({
        connections: []
      });
    }
....
```
How to handle this stuation. I want to avoid having mobserve put everything inside object with enumerated properties.

**Comment by mweststrate** [comment]
Hi Rodry, your question is not entirely clear to me as I am unsure which object you are inspecting in the image. But note that you can directly pass an array to `observable`. Also I recommend using `extendObservable` in constructors, like 

```
constructor(props) {
   extendObservable(this, {
      hosts: {
         connections: []
      }
   })
)
```

The advantage of that is that it makes not only the _value_ of `hosts` observable but also the property itself so that direct property assignments can be picked up in the future automatically.

**Comment by rodryquintero** [comment]
Guys, I decided to drop **Mobservable** for a while and implement the app I am building using **Redux**, which I am more comfortable with. It simply took a long time to solve some of the very particular problems I was facing building it since I am still learning the library.

I plan to publish a repository with the finished app in redux in an effort for the Mobservable community inspect it and perhaps offer ways in which it could have been built using this library.

Refactoring to redux took one afternoon of coding, which tells alot about how good React abstracts from state handlng libs.

Thanks again for responding to all of my issues.

**Comment by mweststrate** [comment]
No problem. Thanks for trying! I look forward to the app, and if you are willing to share any details on the scenarios you couldn't figure out we might try to improve our docs based on that.

**Comment by rodryquintero** [comment]
I will. I am really impresses by Mobservable and still wonder why it has
not been used as often as similar libraries.

Looking forward to give it another try soon.

Thanks again.
