### ISSUE TITLE
Find minimal api surface. Suggestions are welcome!

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/mobservable#11]
Hi all,

Since version 0.3 the api of mobservable has hardly changed so I think probably all the important stuff is in the lib. However, I think the current api surface is too large, and I would like to find & move toward a minimal and comprehensible api in version 0.6. So all ideas are welcome!

Here is an overview of the current api. For a first shot at it, see the next comment.

| method | meaning |
| ---- | ---- |
| | **commonly used methods** |
| `value` | create a observable / reactive value, either wraps `array`, `computed` or `reference` |
| `sideEffect`| make a function reactive, and make sure it is always triggered if one of its dependencies has changed, event if it isn't observed itself | 
| `props(target?, properties)` | creates an observable object, or extends an object with observable properties. Doesn't work recursively. Basically applies `value` to all the values in the `properties` object and adds it to the `target` |
| `fromJson` | turns a JSON tree (acyclic graph) into the same tree in observable form. basically recursively applies `array` and `props` |
| `observable` | property decorator (annotation) for ES6 / typescript, uses `props` internally |
| `ObservingComponent` | ES6 decorator for ReactJS that ensures that a component automatically re-renders if any data it observers changes |
| `ObserverMixin` | same as `ObservingComponent, but for those that do not want to use higher order components but mixins instead. Basically obsoleted by the first one |
| | |
| | **not so commonly used functions** |
| `toJson` | turns a observable tree into a non observable tree (basically a deep copy) |
| `toPlainValue` | turns an observable object, value or primitive into a non-observable copy (basically a shallow copy) |
| `array` | creates an observable array |
| `primitive` | creates an observable scalar. |
| `reference` | creates an observable scalar. alias for `primitive`. Use this if you want to create an observable that refers to a function or array, instead of turning those into an observable as `value` would do 
| `computed` | turn a function into a reactive one |
| `expr` | `expr(func)` is an alias for `computed(func)()`, which might be useful if you created observable functions inside observable functions |
| `observeProperty` | create an observer on a certain property. seems to be obsoleted by `sideEffect with which you can achieve the same |
| `watch` | observe an expression until it needs to be recomputed. Then invokes a callback instead of applying the actual computation, basically useful to build integrations with other frameworks |
| `batch` | apply a set of updates but doesn't notify any observers until all updates are executed. basically an optimization |
    
@dslmeinte @ebrpol do you guys have any suggestions on this?

**Comment by mweststrate** [comment]
My first shot on the complete api (all unmentioned items will be deprecated):

| Old name | New name | Comments |
| --- | --- | ---|
| `value` | `toObservable` or `makeReactive` | See below |
| `sideEffect` | | as-is |
| `props` | `defineProperties` | |
| `fromJson` | | as-is |
| `observable | | as-is |
| `ObservingComponent` | `Reactive` | in own `React` namespace?  |
| `toJson` | | as-is |
| `watch` | `observeUntilInvalid` | |
| `batch` | `transaction` | see #9, use it also to be able to change protected values |
| `toPlainValue` | ?? | |

**toObservable**

In favor of having `value`, `computed`, `array`, `primitive` and `reference` it might be simpler to have just one function, `toObservable` (or to `toReactive`) that automatically created the correct type of observable (basically what `value` does ATM). But instead of having the other variations, I suggest to give it a second property with options, something like:

```
{
	type: 'auto' (default) | 'reference' | 'structure'
	protected: boolean (false)
	scope: Object
	trace: boolean (false)
	name: string
}
```

* `type` can be used if you want to create an observable `reference` to a function, instead of a reactive function, for example. The `structure` option can be used to implement #8 without increasing the API surface
* `protected` disables changing the observable if not in a transation, see #9.
* `scope` is the `this` context for reactive functions
* `trace` and `name` could be used in the future for logging debugging, so that all changes can be logged to the console

Maybe the above options object can also be used in combination with `fromJson`, for example:

```
import { fromJson, withOptions } from mobservable

var observableFunctionRef = toObservable(someFunc, { type: 'reference' });

var someObject = fromJson({
   location: withOptions({  x: 3, y: 2}, { type: 'struct' })
})
```

**Comment by mattmccray** [comment]
It seems rather like `fromJson(obj)` could be the same as a `makeReactive(obj, { recurse:true })`. So `recurse` is probably a poor name, but it would be an option for makeReactive/toObservable that would recurse into the object/array.

Or is that not realistic?

Although I admit, `withOptions` would let you apply different options to sub-tree elements. Not something I foresee using a lot, but interesting. :smile:

That said, `fromJson` is nicely symmetrical to `toJson`... I guess it depends on exactly how svelte you want the api to be.

**Comment by mweststrate** [comment]
`makeReactive` could indeed be combined with a `recurse` option, that makes a lot of sense. It could then even be combined with `withOptions()` wrappers inside its value. So in that case `fromJson` doesn't have a meaning anymore indeed. 

I feel it would clearify some of the current examples, so I think this is a good direction. 

It looses the symmetry with toJson indeed, but on the other hand I'm not sure how important `toJson` really is; it won't work for structures that have cyclic references and besides JSON.stringify works correctly on observable structures already. Or we call it `fromReactive` :)

**Comment by mattmccray** [comment]
Ah, yeah. Good point about `JSON.stringify`. So `toJson` is really more `toPlainObject`.

**Comment by mweststrate** [comment]
What should the following statement do?
`var x = makeReactive(someObject)`

1. create a reactive reference to someObject (as `value` does in 0.5)
2. make someObject a reactive object (as `props` / `fromJson` does in 0.5)
3. if someObject is a plain object (no prototype), _2._ otherwise, _1._

**Comment by mattmccray** [comment]
This is merely my two cents... 

I think option **3**. `makeReactive` is a sufficiently abstract name that is seems like your asking mobservable to "do the right thing." Which, to me, means different things based on the input. So some "smarts" wouldn't be unexpected.

**Comment by mweststrate** [comment]
I think your right! The beauty is that even if you put a plain object in it, and later replace it, that still works as expected as the reference to its is observable anyways, regardless whether it is a plain object or not :)

To take it even further, maybe recurse should have the option 'auto' which is the default. With auto, `makeReactive` recurses into any *plain* object. That is probably what you want when you provide raw json and sounds like a sane default that gets you up and running quickly.

**Comment by mweststrate** [comment]
Another one: what if an function is encountered in the json tree? I think zero argument functions (getters) should be turned in reactive functions automatically (current behavior). But what for multi arguments functions?

1. Keep as-is (maybe log warning)
2. turn into reactive function (see #12)
3. turn into reactive side effect (see #12)
4. throw

I think option 1. is the least confusing one? But if `makeReactive` is explicitly invoked on a multi argument function, option `2` should be applied IMO.

(The difference between 2 and 3, is that reactive functions are lazy (they are not recomputed if nobody observes) and do not require manually cleanup. Side effects are always executed, because there side effect might be needed for something. They have to be stopped manually though)

**Comment by mweststrate** [comment]
Another one: instead of introducing `recurse` we could also make the whole reactive thing infective, so that if you add an entry to a reactive array, that entry will be first run through `makeReactive` itself. And the same holds for any plain object that is assigned to a reactive property. 

This might avoid a lot of `makeReactive` calls; once the root of a store / controller is made reactive, every plain object that is somehow added to it will become reactive as well. 

Might be a bit magical on one side, but on the other hand it prevents bug that are introduced when you forget to make something reactive. To summarize:

```javascript
var todos = makeReactive( [ {
    title: "foo"
} ] );

todos.push(makeReactive( { // forgetting this makeReactive introduces a subtle bug; 
// the todo item won't be reactive, but you only notice that once you start changing it, and not initially
    title: "bar"
} ));
```

would become:

```javascript
var todos = // ...

todos.push({
    title: "bar"
});
```

**Comment by dslmeinte** [comment]
Instead of `makeReactive`, `asReactive`?

I would take `recurse=true` as the default indeed: it feels more "monadic". I'm not so fond of options setters (although they are way better than boolean optional options), so maybe have `asSingleReactive` for the non-recursive variety. Or maybe even leave it out until someone needs it?

W.r.t. functions: to make them truly reactive, why not memoise the invocations?

**Comment by mweststrate** [comment]
I think `makeReactive` makes a bit more clear that you get a new data structure compared to `asReactive` or `toReactive` instead of doing an in-place update

**Comment by mattmccray** [comment]
Yeah, I do have to keep reminding myself to use `fromJson` whenever I merge results into my state graph.

**Comment by mweststrate** [comment]
@dslmeinte can you eloborate where you would apply memoization? I usually find it a dangerous pattern to apply genericly, because you don't know the argument space? 

Shorthands like `asSingleReactive` and `makeReactiveReference` might become in handy, but I think it is a good idea to let that kind of shorthands be request driven.

**Comment by mweststrate** [comment]
@mattmccray exactly, I run into the same thing when writing the example on the website. The new api solves that

**Comment by mweststrate** [comment]
The latest proposal summarized

# makeReactive(thing, options)

`makeReactive` is the swiss knife of `mobservable`. It converts `thing` to something similar, but reactive, based on the type of `thing`.
The following types are distinguished:

* `Primitive`, boolean, string, number, null, undefined, date
* `PlainObject` raw javascript objects that do not created using a constructor function
* `ComplexObject` raw javascript object that was created using a constructor function
* `Array`
* `ViewFuncion` function that takes no arguments but produces a value
* `ComplexFunction` function that takes one or more arguments and might produce a value

`options` is a javascript option map with the following properties:

* `as` specifies what kind of reactive object should be made. Defaults to `"auto"`. Other valid values are `"reference"`, `"struct"` (in a later version see #8). 
* `protected` defines whether a value can be modified outside a transaction. Defaults to `true`. To be added in a later version (see #9)
* `scope` defined the `this` of reactive functions. Will be set automatically in most cases
* `recurse` default `true`, if false, `makeReactive` won't recurse into the data structure nor will values assigned to the structure later on be converted automatially to reactive values
* debugging options like `trace` and `name` might be added later

makeReactive will not go into objects that already have been processed by `makeReactive` or `defineReactiveProperties`. `makeReactive` will also be the default export of the `mobservable` module.

## Direct invocation

`makeReactive` will created the following kind of objects when invoked directly on a value:

* `Primitive`: create a getter/setter observable function that holds the value
* `PlainObject`: returns a deep copy of the object. Calls `makeReactive` recursively on its values. (unless `recurse` was set, in which case you get a shallow copy)
* `ComplexObject`: that is a noop, returns the complex object itself. Use `defineReactiveProperties` instead. Prints a warning.
* `Array`: same as plain object. Any items added to the array in the future will also be made reactive, unless `recurse === false` 
* `ViewFunction`: returns a reactive version of the function, wrapped in a getter/setter observable function
* `ComplexFunction`: that is a noop, prints warning (maybe later convert to factory? see #12)

## Indirect invocation

`makeReactive` will create the following kind of objects when invoked implicitly (through recursing or future assignments)

* `Primitive`: will create a reactive property on the parent
* `PlainObject`: will created a reactive property that holds a reactive version of the object
* `ComplexObject`: will create a reactive property that holds a reference to the complex object
* `Array`: same as plain object
* `ViewFunction`: creates a property which getter is the reactive version of the function passed in
* `ComplexFunction`: creates a property which holds a reference to the function, but will print a warning as well.


---

Other api methods:

# sideEffect

as-is

# defineReactiveProperties(target, properties)

Was: `mobservable.props`

Applies `makeReactive` to properties (following the implicit rules), adds the properties to `target`. 
No longer accepts a single parameter, to avoid confusion with `makeReactive`.

# Reactive

Was: `ObservingComponent` further as is. Reactjs class decorator.

# ReactiveMixin

Was: `ObserveMixin`. Reactjs Mixin.

# observable

as-is. TS / ES6 property decorator.

# toJson

Converts a (non-cyclic) reactive object back to plain js.

# observeUntilInvalid

was: `watch`.

---

Thats it. Missing stuff? Should stuff be added or named differently? Please shoot!

**Comment by mattmccray** [comment]
:+1:

**Comment by mweststrate** [comment]
The story is atm pretty much feature complete, but the `observable` class property annotation seems to be a strange exception, since we use `reactive` terminology through the rest of the api. Any better suggestion?

**Comment by mweststrate** [comment]
`defineReactiveProperties` -> `extendReactive` (or just `extend`?)

**Comment by mattmccray** [comment]
**defineReactiveProperties**

I'd say `extend` means a lot of different things to different people, in the JS world.

Maybe... `makeReactiveProps`?

```javascript
class FormField {
  constructor( pristine="", validators=[] ) {
    makeReactiveProps( this, {
       pristine, 
       validators,
       value: pristine,
       isDirty() {
         return this.value != this.pristine
       },
       isValid() {
         return this.validators.every( validate => validate( this ) )
       }
    })
  }
}
```

**observable**

Maybe `reactive`... It's a decorator for properties, yeah? So it'd look something like this in the flow of code:

```javascript
class Auth {
  // Currently...
  @observable loggedIn = false

  // Maybe...
  @reactive loggedIn = false
}
```

I don't know, to my eyes, `observable` kinda makes sense there.

**Comment by mweststrate** [comment]
I agree about the `@observable`, lets leave it as is it is. It is nicer to read. 

What makes `makeReactiveProps` also very useful is not only using it in constructor functions, but also to define new reactive properties on existing objects (arrays, existing classes, plain (possible already reactive) objects). In the latter case `extend` seem to be nicer but it will be confusing as well indeed. Maybe `extendReactive` or `reactiveProps`?

**Comment by mweststrate** [comment]
ok `extendReactive` it will be, it nicely mirrors `makeReactive`

**Comment by mweststrate** [comment]
0.6 has been released. Closing the issue now. Thanks for all the feedback!
