### ISSUE TITLE
optionally apply mobservable.observable in place

### ISSUE THREAD

**Issue by capaj** [mweststrate/mobservable#112]
currently there is no way to modify an object in place-there is always new one created which is observable.
I would like to request something like:
```
mobservable.observable(toBeObserved, true)
```
Which would make `toBeObserved` itself into an observable.

**Comment by mweststrate** [comment]
Hi @capaj can you elaborate a bit on this one? Because the following holds: 

```
var x = {};
x === observable(x); // true
```

In contrast, making arrays observable indeed always yields new objects. This is mainly because the `.length` property of an array cannot be intercepted (until ES6 proxies)

**Comment by capaj** [comment]
Thanks @mwestrate. I did not realize that yesterday at 5 am in the morning.
