### ISSUE TITLE
Add support for multi argument reactive functions

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/mobservable#12]
Currently `computed` / `value` only supports functions without arguments, that is, getters.

However, supporting functions with arguments might be nice as well; functions that take a combination of observables and turns it into new observables. (Observable factories)

For example
```javascript
import {computed, array} from 'mobservable'

var reactiveConcat = computed((listA, listB) => array([].concat(listA,listB)))

var reactiveResultList = reactiveConcat(someReactiveList, otherReactiveList)
```

where `computed(func)` for `func.length > 0` equals:

```javascript
function computed(func, scope?) {
    return function() {
        args = arguments;
        return computed(() => {
            value(func.apply(scope, args));
        });
    }
}
```

And same pattern for `sideEffect`

**Edit: return value should be made reactive as well**

**Comment by mindeavor** [comment]
Is there an official solution for this? I'm trying to write a generic component abstraction over mobx, and I think I need parameters for computed functions. For example:

```js
function myView (state, observableArray) {
  return observableArray.map(...)
}

var finalView = createComponent(myView)

finalView() //=> should be a function with mobx data-dependency goodness! :)

// Generic component creater
function createComponent (view) {
  var state = {}
  var component = mobx.computed( (...args) => view(state, ...args) ) // <-- Doesn't work :(
  return component
}
```

**Comment by mweststrate** [comment]
@mindeavor  What kind of components are you talking about? For react components it should be enough to wrap them in `observer`. Note that `computed`  doesn't depend on arguments, it will just react to any observables used in the function body, so I think you could write `createComponent` simply as 

```
function createComponent (view) {
  var state = {}
  var component = (...args) => mobx.computed( () => view(state, ...args) ).get()
  return component
}
```

**Comment by mindeavor** [comment]
Thanks for the reply :) I'm trying to get Mobx to work with other VDOM libraries. `state` should be persisted across all view redraws, but `args` can change depending on the parent component.

If I'm not mistaken, the version you suggested will create a new `mobx.computed` on every redraw, losing the benefit of "update only as necessary". My example was probably too stripped down to get the full picture, so here's a fuller example:

```js
var m = mithril

var idCounter = 10
var tasks = mobx.observable([
  { id: idCounter++, name: "Learn Mithril" },
  { id: idCounter++, name: "Learn Mobx" },
])

// Goal: Don't recalculate this component's view unless observable data changed.
// createComponent is defined at bottom.
var TaskComponent = createComponent(function (state, task) {

  return m('li.task', [
    m('input[type=checkbox]', {
      checked: state.isChecked, // Contrived example of component state
      onchange: function () { state.isChecked = this.checked }
    }),
    task.name
  ])
})


function render () {

  m.render(document.getElementById('app'), [
    m('ul', [
      tasks.map( t => TaskComponent(t.id, t) ) // Usage of component
    ]),
    m('input'),
    m('button', {
      onclick: function () {
        tasks.push({ id: idCounter++, name: this.previousSibling.value })
      }
    }, "Add Task")
  ])
}

mobx.autorun(render)

// Generic component builder
function createComponent (view) {
  view.instances = new Map()

  return function (key, ...args) {
    var instance = view.instances.get(key)

    if ( ! instance ) {
      var state = {}
      var computedView = mobx.computed(view) // <-- !

      instance = { state: state, render: (...a) => computedView.get(...a) }
      view.instances.set(key, instance)
    }

    return instance.render(...args)
  }
}
```

Note that this idea works perfectly if I move all the code/logic from `createComponent` into a hand-built TaskComponent directly. Of course, ideally I won't have to do that for every component I create :)

**Comment by mweststrate** [comment]
I have to take a closer look, but note that:

> If I'm not mistaken, the version you suggested will create a new mobx.computed on every redraw,

Is probably no issue, if the only cause for redrawing is that the computed was invalidated anyway. Btw for futher follow, would you mind opening a new separate issue instead of reviving a really old one :) (only just found the notification of your message back in my inbox)

**Comment by mindeavor** [comment]
Ok, will do :)

**Comment by mweststrate** [comment]
Mobx-util's `computedFn` now supports creating computeds for functions with arguments: https://github.com/mobxjs/mobx-utils#computedfn
