### ISSUE TITLE
Why are todoStore methods defined outside the todoStore object?

### ISSUE THREAD

**Issue by dschalk** [mweststrate/mobservable#13]
In the README example, It seemed odd to define the todoStore methods addTodo, removeTodo, and loadTodosAsync outside of todoStore rather than inside like completedCount. I tried to put the method definitions inside of todoStore and the app failed every time. I ended up with this ES6 version:
```javascript
import mobservable from 'mobservable';
import React from 'react';
var todoStore = mobservable.makeReactive({
    todos: [
        {
            title: 'Find a clean mug',
            completed: true
        },
        {
            title: 'Make coffee',
            completed: false
        }
    ],
    completedCount: function() {
        return this.todos.filter((todo) => todo.completed).length;
    },
    pending: 0
});

todoStore.addTodo = (title) => {
    todoStore.todos.push({
        title: title,
        completed: false
    });
};

todoStore.removeTodo = (todo) => {
    todoStore.todos.splice(todoStore.todos.indexOf(todo), 1);
};

todoStore.loadTodosAsync = () => {
    todoStore.pending++;
    setTimeout(function() {
        todoStore.addTodo('Asynchronously created todo');
        todoStore.pending--;
    }, 2000);
};

class ToList extends React.Component{
    render = () => {
        var store = this.props.store;
        console.log(this.props);
        return (<div>
            <ul>
                { store.todos.map((todo, idx) =>
                    (<TodoView store={ store } todo={ todo } key={ idx } />)
                ) }
                { store.pending ? (<li>Loading more items...</li>) : null }
            </ul>
            <hr/>
            Completed { store.completedCount } of { store.todos.length } items.<br/>
            <button onClick={ this.onNewTodo }>New Todo</button>
            <button onClick={ this.loadMore }>Load more...</button>
        </div>);
    }

    onNewTodo = () => {
        this.props.store.addTodo(prompt('Enter a new todo:', 'Try mobservable at home!'));
    }

    loadMore = () => {
        this.props.store.loadTodosAsync();
    }
};

class ToView extends React.Component{
    render = () => {
        var todo = this.props.todo;
        return (<li>
            <input type='checkbox' checked={ todo.completed } onChange={ this.onToggleCompleted } />
            {todo.title}{' '}
            <a href='#' onClick={ this.onEdit }>[edit]</a>
            <a href='#' onClick={ this.onRemove }>[remove]</a>
        </li>);
    }

    onToggleCompleted = () => {
        this.props.todo.completed = !this.props.todo.completed;
    }

    onEdit = (e) => {
        e.preventDefault();
        this.props.todo.title = prompt('Todo:', this.props.todo.title);
    }

    onRemove = (e) => {
        e.preventDefault();
        this.props.store.removeTodo(this.props.todo);
    }
};
let TodoView = mobservable.reactiveComponent(ToView); 
let TodoList = mobservable.reactiveComponent(ToList);
React.render(<TodoList store={todoStore} />, document.getElementById('approot'));
```
It is fully functional, but I still can't define the methods inside of the todoStore object. 

I admit that I haven't thoroughly studied the Mobservable code. Before I do, I wonder if you might  give me a hint or two regarding what is going on with defining methods outside of objects. I am very impressed with the fresh thinking behind this library, and with the elegant simplicity of Mobservable, especially in comparison with Flux and its progeny.  I am eager to use it, but first I want to prepare a little for whatever surprises might lie ahead.

**Comment by mweststrate** [comment]
Hi david,

The short answer is: the controller functions themselves are not reactieve,
they are imperative but alter reactieve data. Thats why they are defined
outside the makereactieve call. I owe you a longer answer but i am a bit
occupied atm. I hope this points in the right direction.

Op zaterdag 8 augustus 2015 heeft David Schalk <notifications@github.com>
het volgende geschreven:

**Comment by mweststrate** [comment]
@dschalk 

You can easily define reactive properties and normal properties / method on the same object if you use constructor function or  ES6 classes. In that case todostore would like as follows:

With constructor function:

```javascript
function todoStore() {
    mobservable.extendReactive(this, { 
       todos: [
        /* .. */
    ],
    completedCount: function() {
        return this.todos.filter((todo) => todo.completed).length;
    },
    pending: 0
});

todoStore.prototype.addTodo = function(todo) {
   /* ... */
}
```

With ES6 or Typescript classes, you can also use the `mobservable.observable` decorator (annotation):

```javascript
class TodoStore {

   @observable todos = [];
  
   @observable get completedCount() {
        return this.todos.filter((todo) => todo.completed).length;
    }

   addTodo(todo) {
      /* .. */
   }
}
```

With both this approaches, `todo` and `completedCount` properties will be reactive. In general you have three kind of things in your classes

1. core data, such as `todos` if you make those reactive you can
2. define derived data, like `completedCount`, which reactively updates when the core data changes
3. methods that alter the core data. Those are not reactive; (otherwise your core data should become reactive data based on the invocation of your actions, which themselves might then become reactive upon the events fired in the browser. Things like RxJs and Baconjs often take this full stack reactiveness. You could do the same with mobservable, but I think that often makes code less understandable)

**Comment by dschalk** [comment]
Thank you Michel. What I vaguely understood yesterday is crystal clear today. I was reluctant to abandon immutable data and the PureRenderMixin, but I no longer have any reservations. I can't think of any reason not to do things the simple, elegant way you have demonstrated.

**Comment by mweststrate** [comment]
Hi @dschalk. The updated docs are progressing steadily, they should make these things more clear. In the mean time, could I quote your last comment on the new homepage guide I'm writing?

**Comment by mweststrate** [comment]
I've updated the docs with details about how (and why) to combine reactive and non-reactive properties to objects. I'll hope that makes stuff clearer for new people.

**Comment by dschalk** [comment]
Here's a link that demonstrates the distinction between defining methods internally or externally: [http://schalk.ninja](http:/schalk.ninja) . Every invocation of "render()" causes an internally defined method to execute, even though nothing related to the method changes. It executes every time I roll over the roll-over buttons.The code is at [https://github.com/dschalk/mobservable-react-buttons](https://github.com/dschalk/mobservable-react-buttons).
