### ISSUE TITLE
Protected Observables

### ISSUE THREAD

**Issue by mattmccray** [mweststrate/mobservable#17]
Would it be useful to have support for "protected" observables? Meaning, reactive values that cannot be set outside of a `transaction` block.

```javascript
import {makeReactive, transaction} from 'mobservable'

export let authInfo= makeReactive({
  authenticated: false,
  authenticatedAt: null,
  currentUser: null
}, {
  protected: true
})

export function login(user, pass) {
  return api
    .authenticate(user, pass)
    .then( user => {
      transaction( _ => {
        authInfo.authenticated = true
        authInfo.authenticatedAt = new Date()
        authInfo.currentUser = user
      })
      return authInfo.currentUser
    })
}

export function logout() {
  transaction( _ => {
    authInfo.authenticated = false
    authInfo.authenticatedAt = null
    authInfo.currentUser = null
  })
}
```

Using the above example, if we were to try directly assigning to a protected value (`authInfo.authenticated = true`) it should fail. 

But would it ignore the input or throw an error? Would mobservable take a performance hit to add this? Is this even a good idea? :fearful: :speech_balloon:

**Comment by mweststrate** [comment]
It is quite do-able to implement this, but I'm still reluctant to say whether such safe guards are the responsibility of Mobservable. So for now I will close the issue, until similar feature requests or more :+1:'s come in.

Thanks for the proposal nonetheless!

**Comment by mattmccray** [comment]
For anyone that stumbles across this -- The feature I'm describing is basically now supported with v2.2's actions: https://mobxjs.github.io/mobx/refguide/action.html

**Comment by mweststrate** [comment]
Also note that `intercept` allows you to guard the access to very specific observables if you want more fine grained control.
