### ISSUE TITLE
Browser support ?

### ISSUE THREAD

**Issue by mehdi-cit** [mweststrate/mobservable#19]
Hello and thank you for sharing this promising library with the community.
It'd be nice to list browser support for mobservable. 
In case it cannot be  used on some common but older browsers, do we know of any shims/polyfills?
Regards.

**Comment by mweststrate** [comment]
Hi,

The library works on any ES5 environment. That means basically any browser
except for IE 8. I tried to use browserling, but it seems to be dead for a
few months already. You could simply verify any specific browser by
opening test/browser/test.html, which runs the test-suite.

Note that the library doesn't actually depend on a browser at all, just a
JS environment that implements the ES5 standard. So all the browsers listed
at
http://kangax.github.io/compat-table/es5/ are supported (but the es5-shim
won't suffice).

Features that won't work on ES3 environments: reactive arrays, objects with
reactive _properties_ (getters). No other features require ES5, although
there might be incidental `.bind` calls in the source, but those can easily
be replaced.

I hope that clarifies!

**Comment by mehdi-cit** [comment]
Thanks a bunch for your prompt and detailed answer!
I do not have all the devices to test on, but according to the link below I should be safe on all smartphones' browsers. 
http://caniuse.com/#feat=es5
The only 'fairly' important browser missing is indeed IE8.

**Comment by nives113** [comment]
I see this is information from 2 years ago. Is this still up to date?
