### ISSUE TITLE
Update JSFiddle examples in blog post

### ISSUE THREAD

**Issue by STRML** [mweststrate/MOBservable#2]
Looks like the new API in 0.5.0 broke your excellent blog post.

I would suggest either pinning the JSFiddles to a commit, or reworking them to use mobservable.ObservingComponent. I have done so in [this update](https://jsfiddle.net/46vL0phw/18/).

**Comment by mweststrate** [comment]
Awesome, thanks! I had it as pending todo, but then I lost my internet connection and forgot about it. Thanks for fixing :)
