### ISSUE TITLE
Permission to quote.

### ISSUE THREAD

**Issue by dschalk** [mweststrate/mobservable#20]
You credited the "I was reluctant . . ." comment in "Five minute introduction to Mobservable + React" to "anonymous programmer". I want you to know that I stand by my words, now more than ever, and you certainly have my permission to  quote me. By the way, my name is "David Schalk", not "Alfred E. Neuman". 

I am changing over to mobservable in my [Websockets React Game of Score](https://www.fpcomplete.com/user/dschalk/Websockets%20Game%20of%20Score) tutorial at "FPComplete. The mouse roll-over, group membership, and find-all-solutions functionality now depend on mobservable. When I am done, "setState" might be completely absent from the code.

**Comment by mweststrate** [comment]
Thanks! Much appreciated :). 

I recognized the picture from the MAD game I have lingering around here somewhere :). Didn't know that a whole history was behind it though.

**Comment by dschalk** [comment]
I created a repository named mobservable-react-buttons at 
https://github.com/dschalk/mobservable-react-buttons.
