### ISSUE TITLE
Create those pretty pictures to show us how mobservable & TFRP works (dnode, etc)

### ISSUE THREAD

**Issue by kenotron** [mweststrate/mobservable#24]
Just a friendly prod from the community to show how this algorithm works. I believe it can take some of the "magic" out and reassure those who want to see inner workings of things before consuming this lib.

**Comment by mweststrate** [comment]
Apologies for not coming back on this issue earlier. I wrote a draft blogpost already a while ago explaining in details the inner workings of Mobservable. But after that I was invited to speak on http://reactive2015.com so I figured I should focus on a 1.0 release and the conference first. So i'll plan to publish this blogpost shortly after the conference. If you can't wait that long, I'm happy to send you the draft in the mean time.

**Comment by kenotron** [comment]
Sure - DM me on reactiflux.slack.com a location for the draft! I am very interested, still.

**Comment by kenotron** [comment]
Oh and good luck on your talk :) Look like a beautiful venue!

**Comment by mweststrate** [comment]
Thanks!

See: https://gist.github.com/mweststrate/9c86eab2cde9d88490a0 for the draft.

**Comment by jameslk** [comment]
I was looking for something like this as well in the documentation. It's explained that view functions will update automatically when any of the dependencies change, but not how that works. My initial uninformed assumption was that the view function was ran anytime any observed value changes, whether it was being used by the view function or not, which would be pretty costly. Then I started playing around and noticed this wasn't the case. I think others doing a cursory review of this library would benefit from a summary of what's behind the sorcery. Overall, though, this stuff is really interesting and I'm looking forward to learning more about it. Thanks for the great work!

**Comment by mweststrate** [comment]
@kenotron @jameslk Ok, it took a while, but the in depth explanation is now online!: https://medium.com/@mweststrate/becoming-fully-reactive-an-in-depth-explanation-of-mobservable-55995262a254#.xpxqzvkur

**Comment by jameslk** [comment]
@mweststrate Awesome, very thorough and informative! I've already started using Mobservable in a new project and it's worked flawlessly so far. You've done a great job!
