### ISSUE TITLE
Confusing results!

### ISSUE THREAD

**Issue by mehdi-cit** [mweststrate/mobservable#25]
Hello,
I did some test with mobservable but I got unexpected results (it does not work for me the way I intended/wanted). Granted, my use case may seem kind of exotic. 
I tried to encapsulate mobservable in some 'isolated' code that we may call 'broker engine'. I need to be able to declaratively define state dependencies between objects that are oblivious to each other. This means, we can have object/modules/components that do not have any reference to anything outside of themselves (totally oblivious to each other). The broker comes into play to declaratively define how these objects' states 'influence' each other. 
First tests were positive, however my little attempt has failed when I started to separate things into encapsulated "areas of concern". Basically when I feed the 'plain old object' into some 'broker engine' to make its data reactive and wire different objects together things break. 
I was able to track where/when things went wrong. Below is a very simple piece of code that describes the behaviour that caught me out of guard: 
```
var x = {a:1, b:2};
var y = x;
x === y; // is true
x = mobservable.makeReactive(x);
x === y; // suddenly becomes false
```
In my mind I would have expected x === y; to remain true. 
Is there a sensible way to achieve the above described behaviour? I mean being able to pass some object X to a separate engine that does apply the magic of mobservable on X's data without loosing that magic because of the inequality "problem" described in the simple code listing above.
I hope I was not too confusing.

Edit: Ooops, Somehow I missed the x at the left side of the assignment in x = mobservable.makeReactive(x); (been copy pasting it). I came back to see the question and it popped to me :)
There's obviously no problem in the simple code listing above :)

**Comment by mweststrate** [comment]
Hi @mehdi-cit 

Yes that is correct, `makeReactive` returns a new object. It could also recycle the same object, but that would probably lead to confusing objects as well. Note that if you want an existing object to become reactive you can just use `mobservable.extendReactive(x, x)`
