### ISSUE TITLE
Sometimes I have to leave a rollover button to get a response, sometimes I don't.

### ISSUE THREAD

**Issue by dschalk** [mweststrate/mobservable#26]
While playing with mobservable (see [Monads](http://transcendent.ninja) and [Buttons](http://schalk.ninja)), I have occasionally encountered what seemed to me to be an inexplicable quirk which I fixed with what seemed to me to be a random hack. It happened again today, and although I am undoubtedly showing my ignorance, I feel I would be remiss if I did not pass this information on.
At [http://transcendent.ninja](http://transcendent.ninja), there is a button that says, "Click to run this.ma2.x.ret([10,20,30]).bnd(this.ma2)". When I define "ma2" as "this.ma2 = new MonadArray([]).x, clicking the rollover button has no effect until I move the mouse pointer out of the button. That triggers a render and the expected result gets displayed. 

I wanted the result to occur when users click the button, not when their pointer leaves it. I solved the problem by defining "ma2" as "this.ma2 = new MonadArray([0,0,0]).x. When the argument is anything but the empty array, clicking the button gets an immediate response.

I made a couple of stabs at trying to understand mobservable.js; but without some annotation, comprehending it right now would be aweffully time-consuming. I'm having too much fun making buttons and monads with what are still, to me, amazing black boxes.

I'm not having any trouble using mobservable. I mention this only on the off chance that I have stumbled upon some edge case that is of interest to you.

-- David

**Comment by dschalk** [comment]
I am glad that you are scheduled to present at the upcoming React conference. You might want to edit the announcement blurb.  "did an interesting discovery" should be "made an interesting discovery" and there is an extraneous period after "React" in the third sentence.

**Comment by dschalk** [comment]
RESOLVED

This is not a mobservable issue. I re-defined "MonadObject" without making it reactive. It has nothing to do with mobservable in its present state, and I am seeing the phenomenon again. If it is a bug, it is Babel's or Ecmascript 2015's bug, not yours.

**Comment by dschalk** [comment]
Update. I made my object monad reactive, and now clicking gives an instant response. I don't need to move the mouse off of the button. 

It is ironic that a problem I mistakenly thought was rooted in Mobservable turns out to be solvable by Mobservable. Sorry about wasting your time with what turned out to be a non-issue..

**Comment by mweststrate** [comment]
No problem, I wasn't able to look into it yet so far, so I'm glad it has been resolved anyway :)
