### ISSUE TITLE
Behavior clarifications

### ISSUE THREAD

**Issue by STRML** [mweststrate/MOBservable#3]
Could you clarify the following snippets from the docs:

> * *synchronous*. All updates are processed synchronously, that is, the pseudo expressions a = 3; b -> a * 2; a = 4; print(b); will always print 4; b will never yield a stale value (unless batch is used).

Do you mean that this will print `8`? If `a = 4` and `b = -> a * 2`, `b() === 8`.

> * *atomic*. All computed values will postpone updates until all inputs are settled, to make sure no intermediate values are visible. That is, the expression a = 3; b -> a * 2; c -> a * b; a = 4; print(c) will always print 36 and no intermediate values like 24.

After `a` is set, the state is: `a = 4`, `b = -> a * 2`, `b() === 8`, `c = -> a * b`, so `c === 32`.

Am I off base somewhere?

**Comment by mweststrate** [comment]
This is embarrassing :cold_sweat: But you are absolutely right, I've updated the README accordingly. Thanks for reading so carefully.
