### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/mobservable#34]
Hi all,

Mobservable is quite stable for a while and feels (imho) quite complete. So it's time to work to a 1.0 release. Here are some ideas for 1.0

## Improvements

1. [x] disable consistency checks in production mode for improved performance
1. [x] simplify error handling for fail fast behavior
1. [x] include typescript 1.6 typings
1. [x] docs docs docs
1. [ ] improved [mobservable-react-devtools](https://github.com/mweststrate/mobservable-react-devtools#roadmap) (see the readme for the ideas) (post 1.0)
1. [ ] support nested transactions (post 1.0)
1. [ ] add some utilities to create observables based on time, which is nice for animations and such? (post 1.0)
1. [ ] extend observable objects with utility methods to remove, add and iterate reactive properties? (post 1.0)

## Breaking changes

1. [x] rename `makeReactive` to `observable`, to nicely mirror the earlier released rename from `sideEffect` to `observe.
1. [x] rename `@observable` (the property annotation) to `obervableProperty` or `observableSubject` -> will remain `@observable`, the signatures could be overloaded
1. [x] rename `@reactiveComponent` to `@observer`
1. [x] throw away all already deprecated api's.
1. [x] the `observable` function (formerly `makeReactive`) will no longer be the root export of the module export itself. It will be the `default` export though.
1. [x] `extendReactive` -> `extendObservable`
1. [x] `isReactive` -> `isObservable`
1. [x] `observe*` -> `autorun*`

## Wild ideas

Actually I don't like the name of the module. Initially it wasn't planned to open source it, so it got a boring name. So if people are not too much hindered by it, it might be cool to give it a better name. So cool name suggestions are welcome! (or if you don't like a new name feel free to mention it as well)

Some of my personal ideas:
* fume
* (...might add more later)

**Comment by chauthai** [comment]
+1 for observableSubject
And as a rename for the package MOS or mos. The short form of mobservable. You don't even have to change the logo... haha

**Comment by kenotron** [comment]
I suggest that if the above list contains features, that you keep that post 1.0 release. Clean up your API a bit with some name / aliasing to make 1.0 docs use the new syntax while allowing folks an on-ramp to your 1.0 APIs. Then after 1.0, you have the opportunity to add new features. I use this lib, and would really prefer that you keep the core of the lib very small as it stands now, and add on to it as small modules.

Name suggestion, based your "fume" name: 

flume - a deep narrow channel or ravine with a stream running through it.

**Comment by mweststrate** [comment]
@kenotron: Yes most of the improvements are ideas at this stage which will be released (if ever) post 1.0. The renames will be part of 0.1, as these will be breaking changes, and maybe the simplified error handling. Currently mobservable is quite resilient to exceptions in views, but I think a fail fast approach might be easier to debug and urges users more to make their own code resilient.

Thanks for the name suggestion!

**Comment by mweststrate** [comment]
Still not convinced that `mobservable.observe` is the proper name, Meteorjs calls it `autorun`, probably that name makes it better clear what it does?

**Comment by mweststrate** [comment]
1.0 has been released! Check the [release notes](https://github.com/mweststrate/mobservable/blob/master/CHANGELOG.md) :)
