### ISSUE TITLE
Expose some of the inner classes to allow for `instanceof` checks

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/mobservable#40]
As reported in #38, it should be easier to check whether an object is an `ObservableArray`, `ObservableObject` or `ObservableMap`. Either expose their classes or introduce `isXXX` methods

**Comment by mweststrate** [comment]
Hi @tetsuo,

In the 1.0.4 version that was released yesterday the methods `isObservableMap`, `isObservableObject` and `isObservableArray` where added. Does this suffice?

**Comment by tetsuo** [comment]
:+1:  It is now also possible to require them directly.
