### ISSUE TITLE
Create integration with RxJS

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/mobservable#57]
It should be possible to convert RxJS observables into Mobservable observables and vice-versa. Can probably be used by users to build debounce (see #48) and more time related patterns.

**Comment by chicoxyzzy** [comment]
would love to see this implemeted

**Comment by xgrommx** [comment]
I agree with @chicoxyzzy. It should be nice.

**Comment by Keats** [comment]
I saw a lot of people mentioning https://github.com/cujojs/most as well

**Comment by mweststrate** [comment]
Personally I have no experience with most, but the idea is pretty similar
right?

Anyway, if some people that already did integrated Mobservable with RxJs /
most / baco; feel free to share your solutions :) That would be very useful
to verify the solution (which will most probably be a separate package)

On Wed, Dec 23, 2015 at 6:46 PM, Vincent Prouillet <notifications@github.com

**Comment by chicoxyzzy** [comment]
@mweststrate is there any way to add custom callback to `disposerFunction `? I am working on Mobservable / Rx interop right now so I need a way to dispose Rx `Subject` on Mobservable's observable dispose

**Comment by chicoxyzzy** [comment]
I think I have a workaround for now so I'll publish my package soon

**Comment by mweststrate** [comment]
awesome!

Otherwise, DNode.onceSleep might do the trick:
https://github.com/mweststrate/mobservable/blob/feature/transform/src/dnode.ts#L303

Not in master yet, will be soon. obtaining a dnode can done by calling `extras.getDNode` on a disposer func or an object (+ property name)

**Comment by chicoxyzzy** [comment]
I'll check it out soon. Here is my [repo](https://github.com/chicoxyzzy/rx-mobservable). Can someone test it and provide some feedback?

**Comment by mweststrate** [comment]
Looks nice and straight forward!

Some suggestions for improvement: 
1. I think it is nice to add a second property name parameter to `mobservableToRx`, so that individual object properties can also be observed easily. I just added support for such a second param to `mobservable.observe` as well in 1.1.8 (see #59).
2. In the disposer of `rxToMobservable` the `mobservable()` call is unnecessary I think.
3. what should happen on Rx end / error events? For both it might be interesting to pass special values into the mobservable observable so that observers can see that the backing stream has ended and no new values should be expected. That enables observers to cleanup by no longer using the observable value (which can be GC-ed after that).
