### ISSUE TITLE
Transactions: cannot read property 'markReady' of undefined

### ISSUE THREAD

**Issue by kmalakoff** [mweststrate/mobservable#65]
I think the logic [here](https://github.com/mweststrate/mobservable/blob/master/src/dnode.ts#L49) is to catch some updating changes mid-update.

However, It looks like `markReady` can alter the changedValues array values which is causing the 'cannot read property 'markReady' of undefined' error.

Should the solution be:

```
           var length_1 = changedValues.length;
            for (var i = 0; i < length_1; i++)
                !changedValues[i] || changedValues[i].markReady(true);
            changedValues.splice(0, length_1);
            if (changedValues.length)
                throw new Error("[mobservable] Illegal State, please file a bug report");
```

or 

```
            var values = changedValues.splice(0);
            for (var i = 0, len = values.length; i < len; i++)
                values[i].markReady(true);
            if (changedValues.length)
                throw new Error("[mobservable] Illegal State, please file a bug report");
```

or do you need me to try to figure out why the issue is happening in the first place? (I've got a transaction that does quite a variety of actions so perhaps values could be removed mid update, but there are done being added so it is not the `Illegal State`).

**Comment by mweststrate** [comment]
If you could find the cause that would be nice :) Although a defensive copy
here would be wise in any case. A possible cause might be starting a
transaction in a computed expression or autorun. In such a way that
finishing one transaction kicks of another one. if I look at this code I
think that might go wrong. Especially the second solution would fix such a
situation (which should be supported).

**Comment by kmalakoff** [comment]
Stepped through a test case. It was like you suspected that a transaction was being triggering during the processing of another transaction.

Basically, in the short term (until your cool "Reactive graph transformations" come through!), I was batching up a bunch of changes and periodically running them in a transaction which then triggered the rendering transaction mid-processing.
