### ISSUE TITLE
Comparative documentation

### ISSUE THREAD

**Issue by kmalakoff** [mweststrate/mobservable#73]
I was thinking that it might be good to use language comparisons (No Classes, ES5 Prototypical Inheritance, ES6 without decorators, ES6 with decorators, TypeScript) in the mobservable documentation. 

Here's what I did on [Knockback](https://kmalakoff.github.io/knockback/tutorial_kb_view_model.html). You see in the top right that you can toggle between CoffeeScript and JavaScript so people familiar with or constrained by one feature set can understand how to achieve a solution using that feature set. 

It also would have the benefit of demonstrating best practices and recommended solutions to specific problems to help reinforce how to use the mobservable feature set. That would definitely help me!

**Comment by mweststrate** [comment]
I figured it would probably be best to focus on ES6 + typescript in the 2.0
api & documentation. It makes the api smaller (for example extendObservable
is almost only useful in ES5) as well and ES5 support could be moved to a
single dedicated case.

**Comment by kmalakoff** [comment]
I definitely agree that too many variants is not worth the cost of documenting. I'm only using ES6 with decorators so your proposal would meet my needs.

The person who introduced me to mobservable uses the ES5 syntax within an ES6 application because he treats the observable({}) as the basis of a single unified, object-based store instead of getting fancy with classes and decorators. I'm not sure if dropping this usage pattern from the main part of the document would be serve that category of user. I can introduce you if you want to learn more why. 

I do agree that a simpler API with smaller surface area and keeping the document work to a manageable level are a good pragmatic goals!

Still doesn't exclude a comparative-style of documentation though - no need to do this, just thought I'd draw your attention to this option before you redo the docs since you've been talking about eventually needing to update them.

**Comment by mattruby** [comment]
For what it's worth, we're still an ES5 shop and we pour over the docs all
the time.  When we move to ES6, we don't plan on using classes.  We're used
to working through the ES6 examples, but the ES5 examples that just run are
very nice.

On Mon, Dec 14, 2015 at 9:18 AM, Kevin Malakoff <notifications@github.com>
wrote:

> I definitely agree that too many variants is not worth the cost of
> documenting. I'm only using ES6 with decorators so your proposal would meet
> my needs.
>
> The person who introduced me to mobservable uses the ES5 syntax within an
> ES6 application because he treats the observable({}) as the basis of a
> single unified, object-based store instead of getting fancy with classes
> and decorators. I'm not sure if dropping this usage pattern from the main
> part of the document would be serve that category of user. I can introduce
> you if you want to learn more why.
>
> I do agree that a simpler API with smaller surface area and keeping the
> document work to a manageable level are a good pragmatic goals!
>
> Still doesn't exclude a comparative-style of documentation though - no
> need to do this, just thought I'd draw your attention to this option before
> you redo the docs since you've been talking about eventually needing to
> update them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mweststrate/mobservable/issues/73#issuecomment-164463944>
> .
>



-- 
-Matt Ruby-
mattruby@gmail.com

**Comment by mweststrate** [comment]
@mattruby That's worth definitely something! Always good to know which target platforms are in use. I'll make sure ES5 will remain a supported & documented platform.

@kmalakoff I just gave you guys collaborator access to the repo. So if at any time you feel for writing more tests or docs you don't have to go through the hassle of PR's. But don't feel obligated ;).

**Comment by kmalakoff** [comment]
Much appreciated! I'm definitely interested in getting involved...you are real a pleasure to work with and this library is awesome!

Hey, could you send me a way to contact you privately in case we want to brainstorm ideas outside of a specific issue? My email address is in my [profile](https://github.com/kmalakoff)

As for the next version of the documentation, I was thinking about starting to make an outline in the Github wiki where we can start shaping things. Probably starting with a list of use cases more than an outline since I'm not sure what you are targeting, but it could evolve into an outline over time before implementing as docs. Sounds good or do you have a better / different idea?

**Comment by mweststrate** [comment]
Added additional documentation: see http://mweststrate.github.io/mobservable/best/syntax.html

@kmalakoff starting an outline sounds like an excellent idea. External input on the docs is much appreciated; I have a hard time to imagine how the docs are perceived by people new to mobservable. Since I'm somehow already sucked into it ;)

**Comment by mattruby** [comment]
The new docs are very helpful.

On Tue, Dec 15, 2015 at 2:16 PM, Michel Weststrate <notifications@github.com
> wrote:

> Added additional documentation: see
> http://mweststrate.github.io/mobservable/best/syntax.html
>
> @kmalakoff <https://github.com/kmalakoff> starting an outline sounds like
> an excellent idea. External input on the docs is much appreciated; I have a
> hard time to imagine how the docs are perceived by people new to
> mobservable. Since I'm somehow already sucked into it ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mweststrate/mobservable/issues/73#issuecomment-164883998>
> .
>



-- 
-Matt Ruby-
mattruby@gmail.com
