### ISSUE TITLE
TypeScript noImplicitAny compiler flag

### ISSUE THREAD

**Issue by ryanatkn** [mweststrate/mobservable#77]
When using Mobservable in a TypeScript project that uses the `noImplicitAny` compiler flag set to true, I'm getting an error at [this line](https://github.com/mweststrate/mobservable/blob/master/src/simpleeventemitter.ts#L10) of `simpleeventemitter.ts`.

It's fixed by changing this

    listeners:{(data?):void}[] = [];

to this

    listeners:{(data?:any):void}[] = [];

I'd suggest adding this flag to Mobservable's `tsconfig.json` to prevent this from happening going forward. The code seems to already use explicit annotations so this shouldn't be much work to keep up.

    {
      "compilerOptions": {
        "noImplicitAny": true,

Thanks for the great library!

**Comment by mweststrate** [comment]
Added tests and released as 1.1.7. Thanks for reporting!
