### ISSUE TITLE
mobservable.observe vs observe : need update to documention

### ISSUE THREAD

**Issue by jeblister** [mweststrate/mobservable#79]
Hi,
in the [Official documentation](https://mweststrate.github.io/mobservable/refguide/observable.html) the line invoking `mobservable` throw a error `Error: Cannot read property 'observe' of undefined(…)` :
```
import {mobservable, observable} from 'mobservable';
// some code
mobservable.observe(() => console.log(person.labelText));
```

to solve this i use  `observe`.

```
import {mobservable, observable, observe} from 'mobservable';
// some code
observe(() => console.log(person.labelText));
```

is this the best solution ?

**Comment by mweststrate** [comment]
Yes that is correct. `mobservable` isn't a member of the mobservable package, it's a mix up of ES5 & ES6 syntax. I'll adjust it!

**Comment by mweststrate** [comment]
em actually it should be `autorun` instead of observe. In general it is better to use `autorun` which is a lot more powerful then `observe`. (Observe observes just one value, while autorun observes any value that is accessed in it's function?)

**Comment by jeblister** [comment]
thank :+1:
