### ISSUE TITLE
Undo/redo pattern?

### ISSUE THREAD

**Issue by skosch** [mweststrate/mobservable#88]
Hey,

mobservable looks fanstastic – it certainly promises to be much less verbose than even the most concise Redux app. Still, I often do need to support undo/redo stacks. I'm aware of @mweststrate's experiments in #9, but it seems like that didn't go anywhere. If I needed a domain data store with undo-able actions, how should I go about it?

I've come across other non-Flux approaches that try to do this, e.g. https://github.com/omniscientjs/immstruct ... might there be a way of combining those ideas?

Many thanks again for sharing this project with the community!

**Comment by mweststrate** [comment]
Efficient undo / redo is very doable by tracking your state using immutable shared data structures. See for example the reactive [2015 demo](https://github.com/mweststrate/mobservable-reactive2015-demo) which features time travelling and the [createTransformer](http://mweststrate.github.io/mobservable/refguide/create-transformer.html) pattern that can be used to achieve patterns like these.

(another approach is to record patches, see for example these packages: https://www.npmjs.com/package/mobservable-patch-stream https://www.npmjs.com/package/observable-delta-stream or the [extras.trackTransactions](https://github.com/mweststrate/mobservable/blob/693d2d4647b5f773887fec235f793a5d4eb92354/src/extras.ts#L106) api, although that is mainly for debugging)

**Comment by skosch** [comment]
Aha, you just autorun your own serializer ... makes sense, thank you! Now I'd probably want to be able to diff two stored states so that upon undo, I can send a changeset to the server. Unfortunately the two npm packages you linked to (by @tetsuo) are dead ... any idea what happened to them?

**Comment by skosch** [comment]
... actually, never mind: https://github.com/chbrown/rfc6902 would do the job just fine for me.

**Comment by tetsuo** [comment]
@skosch @mweststrate Ah, `observable-delta-stream` and `mobservable-patch-stream` are both experimental. *delta stream* one is very heavy, it walks the entire tree for every change, but I will definitely take a look at the latter.
