### ISSUE TITLE
Make it less work to use stores

### ISSUE THREAD

**Issue by skosch** [mweststrate/mobservable#89]
I'd like to comment on the domain store example in the docs ­– it seems that in practice, there's still significant duplication of code, and Mobservable could likely provide some sort of generic store that can be instantiated to the user's liking. I certainly wouldn't want to write a store for every table or a special class for every single entity in my schema. Generating things from a GraphQL string (#75) is one approach, but I'm not sure it's the easiest (nor the most lightweight) one.

I realize this is somewhat out of scope for Mobservable, but I do think a discussion about how much of this could be provided out of the box would be valuable. In particular, the constructors, updaters and auto-savers¹ seem like they'll be the same for 95% of all cases. This could be in a separate package.

Similarly, I'm sure the transport layer functions can be written in a more-or-less generic style – for instance, I'll simply be having a WebSocket in place spitting out RethinkDB changefeeds. If I didn't have to write the code to handle those, then Mobservable would be an almost-complete replacement for the Meteor client side – but much more simple, flexible and unobtrusive!

I apologize if the above is an imprecise ramble; hopefully you can grasp what I'm getting at and help come up with some rough ideas.

¹ just hail-Mary-passing those changes to the server, as shown in the examples, is probably a bit *too* optimistic for some people. Can we revert the changes if the server sends an error, and expose some sort of observable error log to the user?

**Comment by skosch** [comment]
Alternatively, since I'm simply mirroring a server-side NoSQL DB, I'm considering keeping all of my domain data in a single object, with the first level of keys representing tables, and the second level of keys representing document `id`s.

Any document changeset coming down from the server could easily be applied to the corresponding sub-object by writing `store[table][id] = new_document`. As well, an observer function could be created for each document sub-object, and that observer would call `PUT api.server.com/:table/:id` with any changed data (this would happen through some transport layer abstraction function, obviously, and probably involve storing a serialized copy first in case something goes wrong server-side).

Do you see any downsides to this approach? I'd reckon it's quite a bit simpler than writing store classes.

**Comment by mweststrate** [comment]
Hi @skosch,

You are completely right, this could (and probably should) be generalized. However indeed not as part of Mobservable which I consider to be purely a TRP library + convenience stuff to work with objects, arrays and decorators. Professionally we also use a standardized approach but that one is very specific to our needs.

Standardizing the creation of stores is pretty opinionated as it will have to relate to the framework you (might) be using, the backend communication (do you sync patches, complete docs, complete state tree?) and even the syntax (ES6 decorators & classes or also ES5).

There are currently some ideas to standardize something [around meteor](https://forums.meteor.com/t/making-trp-predicable-pure-and-testable/) but I think Mobservable also deserves a stand-alone simple store implementation. I just didn't find the time to built something like that yet :). 

---

Your suggested approach is valid and very doable. Just be aware to dispose observer methods when objects get deleted :)

**Comment by skosch** [comment]
Perfect, thanks for the quick reply Michel. That all makes sense; I'll be keeping my eyes peeled for further discussions/developments on this.

Thanks also for the reminder about disposing observers ... that's the kind of thing I tend to be forgetful about. :)
