### ISSUE TITLE
observable() signature

### ISSUE THREAD

**Issue by davidmoshal** [mweststrate/mobservable#95]
Hi, am struggling with your example project: mobservable-react-typescript

Typescript is complaining about the signature of this part of the example:
"Invalid arguments, expected 2..3":
```
var timerState = observable({
  secondsPassed: 0
});
```
your core.d.ts file declares the `observable` declaration thus:

`export declare function observable(target: Object, key: string, baseDescriptor?: PropertyDescriptor): any;`

The api makes no mention of additional parameters:
http://mweststrate.github.io/mobservable/refguide/observable.html

Dave

**Comment by mweststrate** [comment]
Hi David, `observable` is both a decorator and a function. As function it always has only one argument, but as decorator it has three params. Not that you need to specify those, it's just the compiler signature of any decorator. So you can use it like

`var state =  observable({ a: b}) or like `class X { @observable a = b }`. See also http://mweststrate.github.io/mobservable/best/syntax.html

**Comment by davidmoshal** [comment]
problem is that Webstorm IDE's typechecking complains about the missing parameter, so I've been using it like this:
```
var timerState = observable({
  secondsPassed: 0
}, null);
```

I'm surprised though, that a library written in Typescript, with t.ds files autogenerated, should have this issue.

Dave

**Comment by mweststrate** [comment]
Hmm, is the `experimentDecorators` compiler option enabled? This can be passed as flag to `tsc` or defined in the `tsconfig.json` file (recommended)
