### ISSUE TITLE
Simple counter app not working

### ISSUE THREAD

**Issue by rodryquintero** [mweststrate/mobservable#96]
Sorry for pasting all this code, but I cannot figure out how something so simple does not work. Perhaps including a similar example in the docs would help.

This is just an app that increments/decrements a counter and it display the current count when changing the app's state. It does not show the current count.

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './app';
import store from './store';

ReactDOM.render(<App store={store}/>,  document.getElementById('root') );

------------
import React, { PropTypes } from 'react';
import { observer } from 'mobservable-react';

@observer
class Tracer extends React.Component {

  render () {
    return (<div>
              <h2>Counter:{this.props.store.count}</h2>
              <button onClick={this.add.bind(this)}>+</button>
              <button onClick={this.substract.bind(this)}>-</button>
            </div>);
  }

  add() {
    let { store } = this.props;

    store.increment();
  }

  substract() {
    let { store } = this.props;

    store.decrement();
  }

}

export default Tracer;

--------------------
import { observable, autorun } from 'mobservable';


const appState = observable({
    count: 0
});

appState.increment = () => {
  appState.count++;
};

appState.decrement = () => {
  appState.count--;
};

/* a function that observes the state */
autorun(function() {
  console.log(appState.count);
});
export default appState;
```

I have been using redux for a while and wanted to give **mobserable** a try. I am intrigued by all of its features.

Thanks in advance.

**Comment by mweststrate** [comment]
This looks fine at first sight and quite similar to this [fiddle](https://jsfiddle.net/wgbe4guu/33/) or this [boilerplate](https://github.com/mweststrate/mobservable-react-boilerplate/blob/master/src/index.js) project. Do you have a repo or jsbin/fiddle in which it can be reproduced?

**Comment by rodryquintero** [comment]
Hello @mweststrate. I figured out the problem. I opted not to use the decorator pattern for @observer and used instead the function when exporting the Tracer module. It now works.

I guess it is a problem with my development setup.

Thanks for the quick response anyways. Here is the change I made.

```
import React, { PropTypes } from 'react';
import { observer } from 'mobservable-react';

class Tracer extends React.Component {

  render () {
    return (<div>
              <h2>Counter:{this.props.store.count}</h2>
              <button onClick={this.add.bind(this)}>+</button>
              <button onClick={this.substract.bind(this)}>-</button>
            </div>);
  }

  add() {
    let { store } = this.props;

    store.increment();
  }

  substract() {
    let { store } = this.props;

    store.decrement();
  }

}

export default observer(Tracer);
```

**Comment by mweststrate** [comment]
Ah, I guess you are using babel 6? Babel6 doesn't (officially) support decorators anymore until the specs are finalized. Downgrading to babel 5 might fix the issue. If you are using typescript, make sure the `experimentalDecorator` compiler option is enabled.
